// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHMhfdYDNGfu6CreXiwbFMWmDMAJwwHc',
    appId: '1:993048592237:web:dce80d9116e2ee36c46464',
    messagingSenderId: '993048592237',
    projectId: 'rtech-63873',
    authDomain: 'rtech-63873.firebaseapp.com',
    storageBucket: 'rtech-63873.firebasestorage.app',
    measurementId: 'G-Z2MSS2S8XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMvsg87-RQvcQt5Go0ubONPNAmPOcqHs',
    appId: '1:993048592237:android:e7d64a4f41fb491cc46464',
    messagingSenderId: '993048592237',
    projectId: 'rtech-63873',
    storageBucket: 'rtech-63873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiAKinWCvE9D1TdXjfHvyIyFunxgc3sZg',
    appId: '1:993048592237:ios:02ed417ce8031e07c46464',
    messagingSenderId: '993048592237',
    projectId: 'rtech-63873',
    storageBucket: 'rtech-63873.firebasestorage.app',
    iosBundleId: 'com.example.w1',
  );
}
